In [2]:
import tensorflow as tf
import numpy as np

In [4]:
# Load TFLite model and allocate tensors.

interpreter = tf.lite.Interpreter(model_path="./data/model2.tflite")
interpreter.allocate_tensors()

In [ ]:
# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Test model on random input data.
input_shape = input_details[0]['shape']
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)

In [5]:
# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

In [6]:
# Test model on random input data.
input_shape = input_details[0]['shape']
#input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
input_data = np.array(np.random.randint(0,1000, size=input_shape), dtype=np.float32)

#input_data = np.array([[1]], dtype=np.float32)
print("input : %s" % input_data)

interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()

# The function `get_tensor()` returns a copy of the tensor data.
# Use `tensor()` in order to get a pointer to the tensor.
output_data = interpreter.get_tensor(output_details[0]['index'])
print("output : %s" % output_data)

input : [[[[350. 560. 169.]
   [735. 712. 159.]
   [  5. 989. 383.]
   ...
   [  9. 835. 895.]
   [177. 411.  45.]
   [213. 870. 169.]]

  [[ 94. 528. 345.]
   [265. 324. 588.]
   [607.   3. 985.]
   ...
   [284. 348. 918.]
   [ 62. 671. 612.]
   [988. 828.  82.]]

  [[690.  42. 753.]
   [ 84. 592. 382.]
   [871. 551. 161.]
   ...
   [426. 962. 854.]
   [215. 368. 374.]
   [169. 776. 842.]]

  ...

  [[955. 811. 355.]
   [740. 516. 458.]
   [178. 649. 831.]
   ...
   [548. 428. 271.]
   [399. 280. 229.]
   [855. 879. 569.]]

  [[ 51.  25. 513.]
   [752.  59. 685.]
   [690. 489. 387.]
   ...
   [151. 165. 409.]
   [506. 136. 829.]
   [722. 695.  46.]]

  [[146. 133. 945.]
   [ 43. 928. 561.]
   [552. 934. 459.]
   ...
   [204. 906. 916.]
   [407. 969.  25.]
   [508. 872. 457.]]]]
output : [[9.98963118e-01 1.03688997e-03 1.15101906e-23]]
